services:
  - type: web
    name: lpsm-player-m3u
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: TOKEN_SECRET
        generateValue: true
